version: "3.7"
services:
  omdbapp:
    container_name: omdbapp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8888:8888 # http
      - 9999:9999 # grpc
    expose:
      - "8888" # http
      - "9999" # grpc
    links:
      - "db:db"
    depends_on:
      db:
        condition: service_healthy
  db:
    container_name: db
    image: mysql:8.0.22
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: supersecretpassword
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080